apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - image: ${IMAGE_TAG}-${SERVICE_NAME}
        name: ${SERVICE_NAME}
        ports:
        - containerPort: ${SERVER_PORT}
        env:
        - name: CONFIG_HOST
          value: "${CONFIG_HOST}"
        - name: CONFIG_PORT
          value: "${SERVER_PORT}"
        - name: SERVER_PORT
          value: "${SERVER_PORT}"
        - name: CONFIG_USER
          value: "${CONFIG_USER}"
        - name: CONFIG_PASS
          value: "${CONFIG_PASS}"
        - name: POSTGRES_URL
          value: "${POSTGRES_URL}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
        - name: EMAIL_USERNAME
          value: "${EMAIL_USERNAME}"
        - name: EMAIL_PASSWORD
          value: "${EMAIL_PASSWORD}"
        - name: EMAIL_SEND_TO
          value: "${EMAIL_SEND_TO}"
        - name: KAFKA_SERVER_URL
          value: "${KAFKA_SERVER_URL}"
        - name: DEF_JAVA_OPTIONS
          value: "${DEF_JAVA_OPTIONS}"

---

apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
  - name: "${SERVER_PORT}"
    port: ${SERVER_PORT}
    targetPort: ${SERVER_PORT}
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${SERVICE_NAME}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-buffers: "64k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers: "64k"
    nginx.ingress.kubernetes.io/fastcgi-buffer-size: "32k"
    nginx.ingress.kubernetes.io/fastcgi-buffers: "4"
    nginx.ingress.kubernetes.io/rewrite-target: ${REWRITE_TARGET}
spec:
  rules:
  - http:
      paths:
      - path: ${PATH_PREFIX}${SERVICE_NAME}/?(.*)
        pathType: Prefix
        backend:
          serviceName: ${SERVICE_NAME}
          servicePort: ${SERVER_PORT}