stages:
- test
- build
- docker
- envsubst
- deploy

variables:
  IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_ARTIFACT: ci-k8s-${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_SHORT_SHA}.yaml
  REWRITE_TARGET: /$$1
  PATH_PREFIX: /${CI_ENVIRONMENT_NAME}/${CI_PROJECT_NAME}/
  SERVER_PORT: 8080
  CONFIG_HOST: config-service
  CONFIG_USER: user
  CONFIG_PASS: config_pass
  POSTGRES_URL: jdbc:postgresql://default.postgres:5432/appointment
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  EMAIL_USERNAME: cloud.technologies33@gmail.com
  EMAIL_PASSWORD: qbNG9dDbNB
  EMAIL_SEND_TO: cloud.technologies33@gmail.com
  KAFKA_SERVER_URL: default.kafka:9092
  DEF_JAVA_OPTIONS: -Xms500m -Xmx500m -XX:+UseContainerSupport

test:
  stage: test
  image: openjdk:13-jdk-alpine
  script:
  - echo "Tests Complete!"

build:
  stage: build
  image: openjdk:13-jdk-alpine
  script:
  - ./mvnw package -DskipTests
  artifacts:
    paths:
    - ./*/target/*.jar
    expire_in: 30 minutes

docker:
  stage: docker
  image: cr.yandex/crp5dhuuq8q568nh0cf0:buildah
  script:
  - buildah login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - >
    for service_name in $(ls *-service -d); do
      export SERVICE_NAME=$service_name
      buildah --storage-driver=vfs bud -t ${IMAGE_TAG}-${SERVICE_NAME} ${SERVICE_NAME}
      buildah --storage-driver=vfs push ${IMAGE_TAG}-${SERVICE_NAME}
    done

envsubst on staging:
  stage: envsubst
  image: cr.yandex/crp5dhuuq8q568nh0cf0:envsubs
  script:
  - >
    for ci_k8s_file in ./*-service/ci-k8s.yaml; do
      dirname=${ci_k8s_file%/ci-k8s.yaml}
      export SERVICE_NAME=${dirname#./}
      envsubst -i $ci_k8s_file -o ${SERVICE_NAME}/${K8S_ARTIFACT}
    done
  artifacts:
    paths:
    - ./*/${K8S_ARTIFACT}
    expire_in: 30 minutes
  environment:
    name: staging
    action: prepare
  only:
  - develop

deploy to staging:
  stage: deploy
  image: gcr.io/cloud-builders/kubectl:latest
  script:
  - >
    for ci_k8s_file in ./*-service/${K8S_ARTIFACT}; do
      kubectl apply --record -f $ci_k8s_file
    done
  environment:
    name: staging
  only:
  - develop