apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - image: ${IMAGE_TAG}
        name: ${SERVICE_NAME}
        ports:
        - containerPort: ${SERVER_PORT}
        env:
        - name: SERVER_PORT
          value: "${SERVER_PORT}"
        - name: CONFIG_USER
          value: "${CONFIG_USER}"
        - name: CONFIG_PASS
          value: "${CONFIG_PASS}"

---

apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
  - name: "${SERVER_PORT}"
    port: ${SERVER_PORT}
    targetPort: ${SERVER_PORT}
  type: ClusterIP
status:
  loadBalancer: {}