apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - image: ${IMAGE_TAG}-${SERVICE_NAME}
        name: ${SERVICE_NAME}
        ports:
        - containerPort: 8888
        env:
        - name: PUBCLIC_SUBPATH
          value: "${PUBCLIC_SUBPATH}"

---

apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  type: ClusterIP
status:
  loadBalancer: {}