#logging:
#    file:
#      name: logs/private-service.log
server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    hikari:
      maximumPoolSize: 5
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: liquibase_db

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /openapi.html
