#logging:
#    file:
#      name: logs/private-service.log
server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    hikari:
      maximumPoolSize: 5