#logging:
#  file:
#    name: logs/public-service.log
server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    hikari:
      maximumPoolSize: 5