server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-service
  profiles:
    active: vault
  cloud:
    config:
      server:
        vault:
          host: ${VAULT_HOST:127.0.0.1}
          port: ${VAULT_PORT:8200}
          scheme: http
          authentication: TOKEN
          token: ${VAULT_TOKEN:00000000-0000-0000-0000-000000000000}
          kvVersion: 2
